location = /about/ { return 301 /about-us/; }
location = /6-ways-to-get-the-most-out-of-your-project-search-software { return 301 /blog/; }
location = /portfolio/commercial/ { return 301 /our-projects/; }
location = /portfolio/electrical/ { return 301 /our-projects/; }
location = /portfolio/home-renovation/ { return 301 /our-projects/; }
location = /portfolio/office-renovation/ { return 301 /our-projects/; }
location = /portfolio/residential/ { return 301 /our-projects/; }
location = /portfolio/stadium/ { return 301 /our-projects/; }
location = /portfolio/waterproofing/ { return 301 /our-projects/; }
location = /home-2/ { return 301 /home-2-2/; }
